# pylint: disable=invalid-name,no-member

"""create base tables

Revision ID: 202512140130
Revises:
Create Date: 2025-12-14 01:30:54.453174

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '202512140130'
down_revision: str | list[str] | tuple[str, ...] | None = None
branch_labels: str | list[str] | tuple[str, ...] | None = None
depends_on: str | list[str] | tuple[str, ...] | None = None


def upgrade() -> None:
    """
    Upgrade schema.
    """

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'watch_targets',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('name', sa.String(length=200), nullable=False),
        sa.Column('url', sa.Text(), nullable=False),
        sa.Column('selector_type', sa.String(length=10), nullable=False),
        sa.Column('selector', sa.Text(), nullable=False),
        sa.Column('processor_type', sa.String(length=50), nullable=False),
        sa.Column('processor_config', sa.JSON(), nullable=True),
        sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('last_status', sa.String(length=20), nullable=True),
        sa.Column('last_raw_value', sa.Text(), nullable=True),
        sa.Column('last_processed_value', sa.Text(), nullable=True),
        sa.Column('active', sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'watch_logs',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('watch_target_id', sa.Integer(), nullable=True),
        sa.Column(
            'run_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False
        ),
        sa.Column('status', sa.String(length=20), nullable=False),
        sa.Column('raw_value', sa.Text(), nullable=True),
        sa.Column('processed_value', sa.Text(), nullable=True),
        sa.Column('error_message', sa.Text(), nullable=True),
        sa.Column('duration_ms', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ['watch_target_id'],
            ['watch_targets.id'],
            ondelete='SET NULL'
        ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(
        op.f('ix_watch_logs_watch_target_id'),
        'watch_logs',
        ['watch_target_id'],
        unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """
    Downgrade schema.
    """

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f('ix_watch_logs_watch_target_id'),
        table_name='watch_logs'
    )
    op.drop_table('watch_logs')
    op.drop_table('watch_targets')
    # ### end Alembic commands ###
